---
- name: Create Gitlab group
  group: name=gitlab state=present gid=2022

- name: Create Gitlab user
  user: name=gitlab shell=/bin/bash uid=2022 group=gitlab append=yes state=present

- name: Ensure Gitlab dir exists
  file: path="{{gitlab_ci_multi_data}}" state=directory owner=2022 group=2022

- name: Install Gitlab Multiple Ci Runner via Docker
  docker:
    state: reloaded
    name: ci-runner
    image: gitlab/gitlab-runner
    restart_policy: always
    pull: always
    # log_driver: fluentd
    # log_opt: "fluentd-tag=docker.gitlab-runner"
    volumes:
      - /var/run/docker.sock:/run/docker.sock
      - "{{gitlab_ci_multi_data}}:/etc/gitlab-runner"

- name: Register the runner
  shell: >
    docker exec ci-runner gitlab-ci-multi-runner register
    -n
    -u "{{gitlab_ci_url}}"
    -r "{{runner_token}}"
    --name "{{runner_name}}"
    --executor "docker"
    --docker-image "node:*"
    --tag-list "docker,node"
