---
- name: Create fluentd group
  group: name=fluentd gid=2422 state=present

- name: Create fluentd user
  user: name=fluentd shell=/bin/bash uid=2422 group=fluentd append=yes state=present

- name: Ensure fluentd dir exists
  file: path="{{fluentd_data}}/{{item}}" state=directory owner=2422 group=2422
  with_items:
    - log
    - etc

- name: Copy fluentd configuration
  copy:
    src: fluent.conf
    dest: "{{fluentd_data}}/etc/cnode.conf"

- name: Install fluentd with docker
  docker:
    name: fluent
    image: hourliert/fluentd-docker-image
    state: reloaded
    restart_policy: always
    pull: always
    ports:
      - "24224:24224"
    env:
      FLUENTD_CONF: "cnode.conf"
    volumes:
      - "{{fluentd_data}}/etc:/fluentd/etc"
      - "{{fluentd_data}}/log:/fluentd/log"
