---
- name: Install Docker mailserver
  hosts: park
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  roles:
    - docker.mailserver
  vars_prompt:
    - name: "smtp_thomas_hourlier_password"
      prompt: "thomas.hourlier@cnode.fr password"
      private: yes

    - name: "smtp_techno_watch_password"
      prompt: "techno.watch@cnode.fr password"
      private: yes

    - name: "smtp_gitlab_password"
      prompt: "git@cnode.fr password"
      private: yes
