---
- name: Deploy Everything
  hosts: park
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
- include: deploy.yml
- include: deploy_mailserver.yml
- include: deploy_gitlab.yml
- include: deploy_owncloud.yml
- include: deploy_plex.yml
- include: deploy_torrent.yml
