---
- name: Install cadvisor with docker
  docker:
    name: cadvisor
    image: google/cadvisor
    state: reloaded
    restart_policy: always
    pull: always
    # log_driver: fluentd
    expose: 
      - 8080
    env:
      VIRTUAL_HOST: "{{cadvisor_host}}"
    volumes:
      # - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
      
# the support is partial until https://github.com/google/cadvisor/issues/771
