---
- name: Create registry group
  group: name=registry state=present gid=7344

- name: Create registry user
  user: name=registry shell=/bin/bash uid=7344 group=registry append=yes state=present

- name: Ensure registry dir exists
  file: 
    path: "{{registry_data}}" 
    state: directory
    owner: registry 
    group: registry

- name: Ensure sub data path exists
  file: path="{{ registry_data }}/{{item}}" state=directory
  with_items:
    - data

- name: Copy htpasswd file
  copy:
    src: htpasswd_registry.cnode.fr
    dest: "{{nginx_data}}/htpasswd/registry.cnode.fr"

- name: Copy vhost file
  copy:
    src: "{{item}}"
    dest: "{{nginx_data}}/vhost.d/{{item}}"
  with_items:
    - registry.cnode.fr_location
    - registry.cnode.fr

# wait for letsencrypt
# - name: Copy ssl certificates
#   copy: 
#     src: "ssl/{{item}}/"
#     dest: "{{nginx_data}}/ssl/"
#   with_items:
#     - registry

- name: Install Registry via Docker
  docker:
    state: reloaded
    name: registry
    image: registry:2
    restart_policy: always
    expose:
      - "5000"
    env:
      VIRTUAL_HOST: "{{ registry_hostname }}"
      LETSENCRYPT_HOST: "{{registry_hostname}}"
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - "{{ registry_data }}/data:/var/lib/registry"

