---
- name: Create postgres group
  group: name=postgres state=present gid=1543

- name: Create postgres user
  user: name=postgres shell=/bin/bash uid=999 group=postgres append=yes state=present

- name: Ensure postgres dir exists
  file: path="{{postgresql_data}}" state=directory owner=postgres group=postgres

- name: Install Postgresql via Docker
  docker:
    state: started
    name: postgresql
    image: postgres
    restart_policy: always
    pull: always
    log_driver: fluentd
    log_opt: "fluentd-tag=docker.postgresql"
    ports:
      - "{{ postgresql_port }}:5432"
    env:
      POSTGRES_PASSWORD: "{{ postgresql_root_password }}"
    volumes:
      - "{{ postgresql_data }}:/var/lib/postgresql/data"


- name: Install PostgreSQL Python Module dependencies
  apt:
    name: python-psycopg2
    state: present

- name: Waiting for PostgreSQL connection
  wait_for: port="{{ postgresql_port }}" delay=1
