---
- name: Ensure nginx htpasswd dirs exists
  file: path="{{nginx_data}}/{{item}}" state=directory
  with_items:
     - htpasswd
     - vhost.d

- name: Copy htpasswd file
  copy:
    src: htpasswd_docker.cnode.fr
    dest: "{{nginx_data}}/htpasswd/docker.cnode.fr"

- name: Copy vhost file
  copy:
    src: vhost_docker.cnode.fr
    dest: "{{nginx_data}}/vhost.d/docker.cnode.fr"

- name: Install docker ui via docker
  docker:
    state: reloaded
    restart_policy: always
    name: dockerui
    image: abh1nav/dockerui
    pull: always
    # log_driver: fluentd
    # log_opt: "fluentd-tag=docker.dockerui"
    expose:
      - 9000
    env:
      VIRTUAL_HOST: "{{dockerui_hostname}}"
      LETSENCRYPT_HOST: "{{dockerui_hostname}}"
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
