---
- name: Create Gogs DB
  postgresql_db:
    login_host: "0.0.0.0"
    login_password: "{{ postgresql_root_password }}"
    login_user: postgres
    name: "{{ gogs_db_name }}"
    state: present

- name: Create Gogs DB User
  postgresql_user:
    login_host: "0.0.0.0"
    login_user: postgres
    login_password: "{{ postgresql_root_password }}"
    name: "{{ gogs_db_user }}"
    db: "{{gogs_db_name}}"
    password: "{{ gogs_db_password }}"
    priv: "ALL"
    role_attr_flags: CREATEDB

# - name: Copy ssl certificates
#   copy: 
#     src: ssl/gitlab/
#     dest: "{{nginx_data}}/ssl/"

- name: Install Gogs via Docker
  docker:
    state: reloaded
    name: gogs
    image: gogs/gogs
    restart_policy: always
    pull: always
    log_driver: fluentd
    log_opt: "fluentd-tag=docker.gogs"
    expose:
      - 3000
    ports:
      - "10022:22"
    links:
      - "postgresql:db"
    env:
      VIRTUAL_HOST: "{{gogs_hostname}}"
      VIRTUAL_PORT: 3000
    volumes:
      - "{{ gogs_data }}:/data"
