---
- name: Ensure OpenVPN dir exists
  file: path="{{openvpn_data}}" state=directory


- name: Install OpenVPN via docker
  docker:
    name: openvpn
    state: reloaded
    image: kylemanna/openvpn
    restart_policy: always
    pull: always
    log_driver: fluentd
    log_opt: "fluentd-tag=docker.openvpn"
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{openvpn_data}}:/etc/openvpn"

# wait for ansible 2.0
# need to run (to gen keys)
# docker run -v "{{openvpn_data}}:/etc/openvpn" --rm kylemanna/openvpn ovpn_genconfig -u udp://{{openvpn_hostname}}
# docker run -v "{{openvpn_data}}:/etc/openvpn" --rm -it kylemanna/openvpn ovpn_initpki
# run the server (ie. run this ansible role)
# generate a client configuration
# docker run -v "{{openvpn_data}}:/etc/openvpn" --rm -it kylemanna/openvpn easyrsa build-client-full {{client_name}} nopass
# and to get client config
# docker run -v "{{openvpn_data}}:/etc/openvpn" --rm kylemanna/openvpn ovpn_getclient {{client_name}} > {{client_name}}.ovpn
