---
- name: Install Redis via Docker
  docker:
    state: reloaded
    name: redis
    image: redis
    restart_policy: always
    pull: always
    log_driver: fluentd
    log_opt: "fluentd-tag=docker.redis"
    # ports:
    #   - "{{ redis_port }}:6379"
