---
- name: Ensure nginx ssl dirs exists
  file: path="{{nginx_data}}/{{item}}" state=directory
  with_items:
     - vhost.d

- name: Copy vhost configuration
  copy:
    src: git.cnode.fr
    dest: "{{nginx_data}}/vhost.d/git.cnode.fr"

- name: Create Gitlab group
  group: name=gitlab state=present gid=2022

- name: Create Gitlab user
  user: name=gitlab shell=/bin/bash uid=2022 group=gitlab append=yes state=present

- name: Ensure Gitlab dir exists
  file: path="{{gitlab_data}}" state=directory owner=2022 group=2022

- name: Create Gitlab DB
  postgresql_db:
    login_host: "0.0.0.0"
    login_password: "{{ postgresql_root_password }}"
    login_user: postgres
    name: "{{ gitlab_db_name }}"
    state: present

- name: Create Gitlab DB User
  postgresql_user:
    login_host: "0.0.0.0"
    login_user: postgres
    login_password: "{{ postgresql_root_password }}"
    name: "{{ gitlab_db_user }}"
    db: "{{gitlab_db_name}}"
    password: "{{ gitlab_db_password }}"
    priv: "ALL"
    role_attr_flags: CREATEDB

# wait for letsencryt
- name: Copy ssl certificates
  copy: 
    src: ssl/gitlab/
    dest: "{{nginx_data}}/ssl/"
    owner: root
    group: root

- name: Install Gitlab via Docker
  docker:
    state: reloaded
    name: gitlab
    image: sameersbn/gitlab
    restart_policy: always
    pull: always
    # log_driver: fluentd
    # log_opt: "fluentd-tag=docker.gitlab"
    links:
      - "redis:redisio"
      - "postgresql:postgresql"
    ports:
      - "10022:22"
    env:
      VIRTUAL_HOST: "{{gitlab_hostname}}"
      LETSENCRYPT_HOST: "{{gitlab_hostname}}"
      LETSENCRYPT_EMAIL: "{{letsencrypt_email}}"
      USERMAP_UID: 2022
      USERMAP_GID: 2022
      GITLAB_HOST: "{{ gitlab_hostname }}"
      GITLAB_PORT: 443
      GITLAB_HTTPS: true
      GITLAB_SSH_PORT: 10022
      NGINX_MAX_UPLOAD_SIZE: 100m
      GITLAB_SECRETS_DB_KEY_BASE: "{{ gitlab_secrets_db_key_pass }}"
      DB_NAME: "{{ gitlab_db_name }}"
      DB_USER: "{{ gitlab_db_user }}"
      DB_PASS: "{{ gitlab_db_password }}"
      SMTP_USER: "{{ gitlab_smtp_user }}"
      SMTP_PASS: "{{ smtp_gitlab_password }}"
      IMAP_ENABLED: false
      IMAP_USER: "{{ gitlab_smtp_user }}"
      IMAP_PASS: "{{ smtp_gitlab_password }}"
      IMAP_HOST: "{{ gitlab_imap_host }}"
      SMTP_HOST: "{{ gitlab_smtp_host }}"
      SMTP_DOMAIN: "{{ gitlab_smtp_domain }}"
      GITLAB_EMAIL: "{{ gitlab_email }}"
      GITLAB_EMAIL_REPLY_TO: "{{ gitlab_email_reply_to }}"
      GITLAB_BACKUPS: "{{ gitlab_backup }}"
      GITLAB_BACKUP_TIME: "{{ gitlab_backup_time }}"
    volumes:
      - "{{ gitlab_data }}:/home/git/data"
