---
- name: Ensure mailserver dir exists
  file: path="{{mail_server_data}}" state=directory

- name: Ensure mailserver postfix dirs exists
  file: path="{{mail_server_data}}/{{item}}" state=directory
  with_items:
     - postfix
     - spamassassin
     - mail

- name: Ensure mailserver postfix ssl dir exists
  file: path="{{mail_server_data}}/postfix/ssl" state=directory

- name: Copy ssl self-signed certificates
  copy: 
    src: ssl/mailserver/
    dest: "{{mail_server_data}}/postfix/ssl/"

- name: Copy postfix configuration
  template:
    src: "{{item}}"
    dest: "{{mail_server_data}}/postfix/{{item}}"
  with_items:
   - accounts.cf
   - virtual


- name: Installing mailserver
  docker:
    name: mail
    image: hourliert/docker-mailserver
    state: reloaded
    pull: always
    restart_policy: always
    hostname: "{{mail_hostname}}"
    domainname: "{{mail_tld}}"
    expose: 
      - 25
      - 143
      - 587
      - 993
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - "{{mail_server_data}}/spamassassin:/tmp/spamassassin/"
      - "{{mail_server_data}}/postfix:/tmp/postfix/"
      - "{{mail_server_data}}/mail:/var/mail"
